- name: Ping arbitrary destination from server
  hosts: all
  tasks:
  - name: "Ping {{ ping_target }} from {{ 15.213.28.199 }}"
    command: "ping -c 5 {{ ping_target }}"
    delegate_to: "{{ 15.213.28.199 }}"
    changed_when: false
    register: ping
  - name: Print output from ping
    debug:
      msg: "{{ ping.stdout }}"
      verbosity: 2
